# Welcome to yourown-bootstrap4!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: Rubin and Rothman, LLC
email: comments@rubinrothman.com
address: 1787 Veterans Memorial Highway <br> Islandia, NY 11749
license: 2045512-DCA
phone: '1-(800)-298-6058'
fax: '1-(631)-234-1138'
description: > #
  Rubin & Rothman, LLC is a New York,
  New Jersey, Connecticut, and
  Massachusetts creditor's rights law firm.


# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js

plugins:
  - jekyll-seo-tag

contact-name-label: Name
contact-email-label: Email
contact-phone-label: Phone
contact-message-label: Message
contact-email-share-text: We'll never share your email with anyone else.

es-contact-name-label: Nombre
es-contact-email-label: Correo electrónico
es-contact-phone-label: Teléfono
es-contact-message-label: Mensaje
es-contact-email-share-text: Nunca compartiremos su correo electrónico con nadie más.

policy-label: PRIVACY POLICY
terms-label: TERMS OF USE
link-policy: /privacy-policy.html
link-terms: /terms-of-use.html

es-policy-label: POLITICA DE PRIVACIDAD
es-terms-label: TERMINOS DE USO
es-link-policy: /es/privacy-policy.html
es-link-terms: /es/terms-of-use.html

es-disclamer: 'This communication is from a debt collector. This is an attempt to collect a debt and any information obtained will be used for that purpose'
disclamer: 'This communication is from a debt collector. This is an attempt to collect a debt and any information obtained will be used for that purpose'
