# Welcome to yourown-bootstrap4!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically.

# Site settings
title: Rubin and Rothman, LLC
email: info@rubinrothman.com
address: 1787 Vetrans Memorial Highway <br> Islandia, NY 11749
license: 2045512-DCA
phone: 800.999.9999
description: > # 
  Important text for SEO


# Build settings
markdown: kramdown

# Exclude nodes artifacts from build
exclude:
  - package.json
  - node_modules
  - gulpfile.js
